# Generated by Django 5.0.1 on 2024-01-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
