# Generated by Django 5.0.1 on 2024-01-15 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_description_band_sold_band_type_band_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
