# Generated by Django 5.0.1 on 2024-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_title_description_title_sold_title_type_title_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
