# Generated by Django 5.0.1 on 2024-01-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_title_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='like_new',
        ),
    ]
