# Generated by Django 5.0.1 on 2024-01-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_band_description_remove_band_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='biography',
        ),
    ]
