# Generated by Django 5.0.1 on 2024-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_band_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='year_formed',
            new_name='annee_de_creation',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='official_homepage',
            new_name='page_officielle',
        ),
    ]
